name: 'IssueWhiz'
description: 'Automated Issue Triaging'
branding:
  icon: 'compass'
  color: 'blue'
inputs:
  ghToken:
    description: 'GitHub Token with write access to repository issues'
    required: true
    default: ''
  openAI:
    description: 'OpenAI Token'
    default: ''
  gemini:
    description: 'Google Gemini Token'
    default: ''
  model:
    description: 'AI model to use'
    default: 'gemini-2.5-flash'
  filter:
    description: 'Lines in the issue text matching these prefixes will be removed prior to LLM evaluation'
    default: ''
  variables:
    description: 'Variable definitions and boolean questions'
    default: ''
  logic:
    description: 'Logic expressions and corresponding actions'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
